name: Local dev

on:
  push:
    branches:
      - main
  pull_request:

permissions:
    contents: read

jobs:
  local-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # TEMPORARY - can remove when no more node-gyp@7.1.0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: End-to-end test the server
        env:
          API_BASE: https://www.peterbe.com
          SERVER_URL: http://localhost:3000
        run: npm run dev > /tmp/stdout.log 2> /tmp/stderr.log &

      - name: Navigate to the server
        run: |
          sleep 3
          curl --retry-connrefused --retry 4 http://localhost:3000

      - name: Debug any server outputs
        if: failure()
        run: |
          echo "___NETSTAT___"
          netstat -nplt
          echo "____STDOUT____"
          cat /tmp/stdout.log
          echo "____STDERR____"
          cat /tmp/stderr.log
